### PR TITLE
Markdown corrections

### PR DESCRIPTION
**Pull request by karegapauline**
…sion.md

@ewels I'm creating pull requests in a separate branch markdown_corrections with all the corrections

## PR checklist

 - [ ] This comment contains a description of changes (with reason)
 - [ ] `CHANGELOG.md` is updated
 - [ ] If you've fixed a bug or added code that should be tested, add tests!
 - [ ] Documentation in `docs` is updated

### CODE REVIEW

**Comment by ewels** [comment]
@karegapauline could you please merge this pull request? We can't do anything with your changes until they are part of the PR on the main nf-core/tools repo.

If you click merge here then they should be appended automatically.

Thanks!

**Comment by karegapauline** [comment]
@ewels sorry for the delay

**Comment by ewels** [comment]
No problem at all! I just didn't want to forget about it by accident 😊

**Comment by ewels** [comment]
Ah wait - [your PR on nf-core/tools](https://github.com/nf-core/tools/pull/1458)  is from your `master` branch and this was into `dev`.

It looks like the commit history starts off the same but then diverges. So I'm a bit lost about what has happened where now.

**Pull request merged**
